name: Pre-commit

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Determine range
        id: sha
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "base=${{ github.event.pull_request.base.sha }}" >>"$GITHUB_OUTPUT"
            echo "head=${{ github.event.pull_request.head.sha }}" >>"$GITHUB_OUTPUT"
          else
            echo "base=${{ github.event.before }}" >>"$GITHUB_OUTPUT"
            echo "head=${{ github.sha }}" >>"$GITHUB_OUTPUT"
          fi
      - name: Run pre-commit
        run: pre-commit run --show-diff-on-failure --color=always --from-ref ${{ steps.sha.outputs.base }} --to-ref ${{ steps.sha.outputs.head }}
